name: PolyPulse Updater

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:      # Allows you to run it manually from GitHub UI

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      - name: Run PolyPulse Scanner
        run: python backend/main.py

      - name: Commit and Push
        run: |
          git config --global user.name 'PolyPulse Bot'
          git config --global user.email 'bot@polypulse.xyz'
          git add data/whales.json
          git commit -m "üê≥ Data Update" || exit 0
          git push
